"""
ACO Route Optimizer - ACO Core Logic + OSRM Route Drawing

This module provides:
1. ACO core algorithm to generate waypoints using environmental factors
2. Returns waypoints, distance, time, environmental values
3. Passes waypoints to OSRM for real route drawing

Author: Way2Sustain Team
"""
import math
import random
import json
import time
from dataclasses import dataclass, field
from typing import List, Dict, Tuple, Optional
from datetime import datetime

# Import environmental cost module
try:
    from backend.aco.environmental_cost import (
        ROUTE_WEIGHTS,
        BASE_EMISSIONS,
        EV_MULTIPLIERS,
        calculate_co2_emissions,
        calculate_edge_emission,
        calculate_eco_points as calc_eco_points,
        calculate_fitness,
    )
except ImportError:
    from environmental_cost import (
        ROUTE_WEIGHTS,
        BASE_EMISSIONS,
        EV_MULTIPLIERS,
        calculate_co2_emissions,
        calculate_edge_emission,
        calculate_eco_points as calc_eco_points,
        calculate_fitness,
    )


# =============================================================================
# DATA CLASSES
# =============================================================================

@dataclass
class RealTimeFactors:
    """Real-time environmental factors for route calculation"""
    traffic_congestion: float = 0.3      # 0-1 scale
    air_quality_index: float = 50.0     # 0-500 AQI
    weather_impact: float = 0.1         # 0-1 scale
    elevation_gain: float = 0.0          # meters
    temperature: float = 25.0           # celsius
    
    def to_dict(self) -> Dict:
        return {
            'traffic_congestion': self.traffic_congestion,
            'air_quality_index': self.air_quality_index,
            'weather_impact': self.weather_impact,
            'elevation_gain': self.elevation_gain,
            'temperature': self.temperature,
        }
    
    @staticmethod
    def generate(seed: int = None) -> 'RealTimeFactors':
        """Generate real-time factors with variation"""
        if seed is not None:
            random.seed(seed)
        
        return RealTimeFactors(
            traffic_congestion=random.uniform(0.2, 0.7),
            air_quality_index=random.uniform(30, 120),
            weather_impact=random.uniform(0.0, 0.4),
            elevation_gain=random.uniform(0, 100),
            temperature=random.uniform(20, 35),
        )


@dataclass
class Waypoint:
    """A waypoint generated by ACO"""
    lat: float
    lon: float
    order: int
    # Environmental values at this waypoint
    elevation: float = 0.0
    road_type: str = 'road'
    estimated_traffic: float = 0.3
    distance_from_prev: float = 0.0
    cumulative_distance: float = 0.0
    
    def to_dict(self) -> Dict:
        return {
            'lat': self.lat,
            'lon': self.lon,
            'order': self.order,
            'elevation': self.elevation,
            'road_type': self.road_type,
            'estimated_traffic': self.estimated_traffic,
            'distance_from_prev': self.distance_from_prev,
            'cumulative_distance': self.cumulative_distance,
        }


@dataclass
class Ant:
    """Represents an ant in the ACO algorithm"""
    id: str
    route_type: str = 'balanced'
    waypoints: List[Waypoint] = field(default_factory=list)
    visited: set = field(default_factory=set)
    fitness: float = float('inf')
    
    # Route metrics
    total_distance_km: float = 0.0
    total_time_minutes: float = 0.0
    total_co2_kg: float = 0.0
    eco_points: int = 0
    
    # Pheromone level
    pheromone: float = 1.0
    
    def reset(self):
        self.waypoints = []
        self.visited = set()
        self.fitness = float('inf')
        self.total_distance_km = 0.0
        self.total_time_minutes = 0.0
        self.total_co2_kg = 0.0
        self.eco_points = 0
        self.pheromone = 1.0


# =============================================================================
# ACO CORE ALGORITHM
# =============================================================================

class ACOCore:
    """
    ACO Core Algorithm - Generates waypoints using environmental factors
    
    The ACO algorithm:
    1. Starts from origin, builds waypoints toward destination
    2. Each ant chooses next waypoint based on pheromone and heuristic
    3. Heuristic considers: distance, traffic, road type, elevation
    4. After iterations, best ant's waypoints are selected
    5. Waypoints are passed to OSRM for real route drawing
    """
    
    # ACO Parameters
    ANT_COUNT = 20
    MAX_ITERATIONS = 15
    ALPHA = 1.0      # Pheromone importance
    BETA = 2.5       # Heuristic importance
    EVAPORATION = 0.4
    Q = 100.0        # Pheromone deposit factor
    
    # Waypoint generation
    WAYPOINT_COUNT = 5  # Number of intermediate waypoints
    SEARCH_RADIUS_KM = 10.0  # Max distance for waypoint search
    
    def __init__(self):
        self.pheromones: Dict[Tuple[int, int], float] = {}
        self.best_ant: Optional[Ant] = None
        self.real_time_factors: RealTimeFactors = RealTimeFactors.generate()
    
    def set_real_time_factors(self, factors: RealTimeFactors):
        """Set real-time environmental factors"""
        self.real_time_factors = factors
    
    def _generate_candidate_waypoints(
        self, 
        start: Tuple[float, float], 
        end: Tuple[float, float],
        count: int,
        route_type: str = 'balanced'
    ) -> List[Waypoint]:
        """Generate candidate waypoints between start and end with route-type specific variations"""
        candidates = []
        
        lat_diff = end[0] - start[0]
        lon_diff = end[1] - start[1]
        
        # Calculate perpendicular direction for offset
        perp_lat = -lon_diff
        perp_lon = lat_diff
        perp_length = math.sqrt(perp_lat * perp_lat + perp_lon * perp_lon)
        if perp_length > 0:
            perp_lat_norm = perp_lat / perp_length
            perp_lon_norm = perp_lon / perp_length
        else:
            perp_lat_norm = 0.0
            perp_lon_norm = 1.0
        
        # Route-type specific parameters
        # eco: much larger offset (winding scenic routes), balanced: medium, quickest: very small offset
        if route_type == 'eco':
            base_offset_km = 15.0  # ~15km deviation from direct path - much more scenic
            random_factor = 0.5
            use_sine_curve = True
            direction = 1.0  # positive perpendicular direction
        elif route_type == 'quickest':
            base_offset_km = 0.5  # nearly direct path - minimal deviation
            random_factor = 0.05
            use_sine_curve = False
            direction = 0.0  # no deviation - straight line
        else:  # balanced
            base_offset_km = 6.0  # moderate deviation
            random_factor = 0.3
            use_sine_curve = True
            direction = -0.7  # opposite direction from eco
        
        # Convert km offset to degrees (approximate)
        km_to_deg_lat = 1.0 / 110.0  # ~111km per degree
        km_to_deg_lon = 1.0 / (111.0 * math.cos(math.radians(start[0])))
        base_offset_lat = base_offset_km * km_to_deg_lat
        base_offset_lon = base_offset_km * km_to_deg_lon
        
        for i in range(count):
            # Progressive position along the route
            t = (i + 1) / (count + 1)
            
            # Base position along direct line
            base_lat = start[0] + lat_diff * t
            base_lon = start[1] + lon_diff * t
            
            # Calculate offset based on route type
            if route_type == 'eco':
                # Eco routes use sine curve for winding paths
                # This creates a more scenic, longer route
                curve = math.sin(t * math.pi)  # 0 -> 1 -> 0
                offset_amount = base_offset_lat * curve * direction
                offset_perp_lat = perp_lat_norm * offset_amount
                offset_perp_lon = perp_lon_norm * offset_amount * direction
            elif route_type == 'quickest':
                # Quickest routes are nearly direct
                curve = 0.0
                offset_amount = base_offset_lat * curve * direction
                offset_perp_lat = perp_lat_norm * offset_amount
                offset_perp_lon = perp_lon_norm * offset_amount * direction
            else:  # balanced
                # Balanced uses partial curve
                curve = (1 - math.cos(t * math.pi)) / 2  # 0 -> 1 -> 0
                offset_amount = base_offset_lat * curve * direction
                offset_perp_lat = perp_lat_norm * offset_amount
                offset_perp_lon = perp_lon_norm * offset_amount * direction
            
            # Add small random variation
            random_offset_lat = random.uniform(-0.01, 0.01) * random_factor
            random_offset_lon = random.uniform(-0.01, 0.01) * random_factor
            
            # Final position
            lat = base_lat + offset_perp_lat + random_offset_lat
            lon = base_lon + offset_perp_lon + random_offset_lon
            
            # Elevation consideration
            elevation = self.real_time_factors.elevation_gain * t
            
            # Estimate road type based on position and route type
            road_type = self._estimate_road_type(t, self.real_time_factors.traffic_congestion)
            
            waypoint = Waypoint(
                lat=lat,
                lon=lon,
                order=i,
                elevation=elevation,
                road_type=road_type,
                estimated_traffic=self.real_time_factors.traffic_congestion,
            )
            candidates.append(waypoint)
        
        return candidates
    
    def _estimate_road_type(self, t: float, traffic: float) -> str:
        """Estimate road type based on position and traffic"""
        # At start/end: residential roads
        # In middle: could be highway or main road
        if t < 0.2 or t > 0.8:
            return 'residential'
        elif traffic > 0.5:
            return 'secondary'
        else:
            return 'primary'
    
    def _calculate_waypoint_cost(
        self, 
        from_wp: Waypoint, 
        to_wp: Waypoint,
        route_type: str
    ) -> float:
        """Calculate cost to travel from one waypoint to another"""
        # Calculate distance
        dist = self._haversine_distance(
            (from_wp.lat, from_wp.lon),
            (to_wp.lat, to_wp.lon)
        )
        
        # Get route weights
        weights = ROUTE_WEIGHTS.get(route_type, ROUTE_WEIGHTS['balanced'])
        
        # Road type cost (lower is better for eco)
        road_costs = {
            'motorway': 3.0,
            'primary': 2.0,
            'secondary': 1.5,
            'tertiary': 1.2,
            'residential': 0.5,
            'road': 1.0,
        }
        road_cost = road_costs.get(to_wp.road_type, 1.0)
        
        # Traffic cost
        traffic_cost = 1.0 + to_wp.estimated_traffic * 0.5
        
        # Elevation cost (hills are harder for eco)
        elevation_cost = 1.0 + (to_wp.elevation / 100) * 0.3
        
        # AQI cost (worse AQI = higher cost for eco routes)
        aqi_cost = 1.0 + (self.real_time_factors.air_quality_index / 200) * 0.2
        if route_type == 'eco':
            aqi_cost *= 1.5
        
        # Calculate total cost
        base_cost = dist
        
        if route_type == 'eco':
            # Eco prioritizes: road type, elevation, AQI
            cost = (
                base_cost * road_cost * 
                elevation_cost * aqi_cost *
                weights.emission_weight * 10
            )
        elif route_type == 'quickest':
            # Quickest prioritizes: direct distance
            cost = base_cost * traffic_cost * weights.time_weight
        else:  # balanced
            cost = (
                base_cost * road_cost * traffic_cost *
                (weights.distance_weight + weights.emission_weight)
            )
        
        return max(0.01, cost)
    
    def _haversine_distance(self, p1: Tuple[float, float], p2: Tuple[float, float]) -> float:
        """Calculate distance in km using Haversine formula"""
        lat1, lon1 = p1
        lat2, lon2 = p2
        
        R = 6371  # Earth radius in km
        
        dlat = math.radians(lat2 - lat1)
        dlon = math.radians(lon2 - lon1)
        
        a = (math.sin(dlat/2)**2 + 
             math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * 
             math.sin(dlon/2)**2)
        c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
        
        return R * c
    
    def _select_next_waypoint(
        self, 
        candidates: List[Waypoint],
        current: Waypoint,
        route_type: str,
        rng: random.Random,
        ant: Ant = None
    ) -> Optional[Waypoint]:
        """Select next waypoint using ACO probability formula"""
        if not candidates:
            return None
        
        # Get visited set from ant if available
        visited = ant.visited if ant else set()
        
        # Calculate probabilities for each candidate
        candidates_with_prob = []
        total_prob = 0.0
        
        for wp in candidates:
            if wp.order in visited:
                continue
            
            # Get pheromone
            key = (current.order, wp.order)
            pheromone = self.pheromones.get(key, 1.0)
            
            # Get heuristic (inverse of cost)
            cost = self._calculate_waypoint_cost(current, wp, route_type)
            heuristic = 1.0 / (cost + 0.01)
            
            # Calculate probability
            prob = (pheromone ** self.ALPHA) * (heuristic ** self.BETA)
            candidates_with_prob.append((wp, prob))
            total_prob += prob
        
        if not candidates_with_prob:
            return None
        
        # Roulette wheel selection
        r = rng.random() * total_prob
        cumsum = 0.0
        
        for wp, prob in candidates_with_prob:
            cumsum += prob
            if cumsum >= r:
                return wp
        
        # Fallback: return best candidate
        return max(candidates_with_prob, key=lambda x: x[1])[0]
    
    def _build_ant_path(
        self, 
        start: Tuple[float, float],
        end: Tuple[float, float],
        route_type: str,
        rng: random.Random
    ) -> Ant:
        """Build a path for an ant"""
        ant = Ant(id=f"ant_{route_type}_{rng.randint(0, 10000)}", route_type=route_type)
        
        # Create waypoints
        # Create waypoints - pass route_type for distinct route generation
        candidates = self._generate_candidate_waypoints(start, end, self.WAYPOINT_COUNT, route_type)
        
        # Start waypoint
        start_wp = Waypoint(
            lat=start[0], lon=start[1], order=0,
            road_type='start'
        )
        ant.waypoints.append(start_wp)
        ant.visited.add(0)
        
        # Build path through waypoints
        current = start_wp
        total_distance = 0.0
        
        for _ in range(self.WAYPOINT_COUNT):
            next_wp = self._select_next_waypoint(candidates, current, route_type, rng)
            
            if next_wp is None:
                break
            
            # Calculate distance from current to next
            dist = self._haversine_distance(
                (current.lat, current.lon),
                (next_wp.lat, next_wp.lon)
            )
            next_wp.distance_from_prev = dist
            total_distance += dist
            next_wp.cumulative_distance = total_distance
            
            ant.waypoints.append(next_wp)
            ant.visited.add(next_wp.order)
            current = next_wp
        
        # Add end waypoint
        end_wp = Waypoint(
            lat=end[0], lon=end[1],
            order=len(ant.waypoints),
            road_type='end'
        )
        dist_to_end = self._haversine_distance(
            (current.lat, current.lon),
            (end[0], end[1])
        )
        end_wp.distance_from_prev = dist_to_end
        total_distance += dist_to_end
        end_wp.cumulative_distance = total_distance
        ant.waypoints.append(end_wp)
        
        # Calculate metrics
        ant.total_distance_km = total_distance
        ant.total_time_minutes = (total_distance / 40) * 60  # Assume 40 km/h average
        ant.total_co2_kg = (BASE_EMISSIONS['electric car'] * total_distance) / 1000
        
        # Calculate fitness
        ant.fitness = calculate_fitness(
            total_distance=total_distance * 1000,
            total_time=ant.total_time_minutes * 60,
            total_emission=ant.total_co2_kg,
            route_type=route_type,
            avg_traffic=self.real_time_factors.traffic_congestion,
            avg_aqi=self.real_time_factors.air_quality_index,
        )
        
        return ant
    
    def _evaporate_pheromones(self):
        """Evaporate pheromones on all edges"""
        for key in self.pheromones:
            self.pheromones[key] *= (1.0 - self.EVAPORATION)
            self.pheromones[key] = max(0.1, self.pheromones[key])
    
    def _deposit_pheromones(self, ants: List[Ant]):
        """Deposit pheromones based on ant solutions"""
        for ant in ants:
            if ant.fitness <= 0 or ant.fitness == float('inf'):
                continue
            
            # Better fitness = more pheromone
            deposit = self.Q / ant.fitness
            
            for i in range(len(ant.waypoints) - 1):
                from_order = ant.waypoints[i].order
                to_order = ant.waypoints[i + 1].order
                key = (from_order, to_order)
                
                self.pheromones[key] = self.pheromones.get(key, 1.0) + deposit
                self.pheromones[key] = min(10.0, self.pheromones[key])
    
    def run_aco(
        self, 
        start: Tuple[float, float], 
        end: Tuple[float, float],
        route_type: str = 'eco',
        seed: int = 0
    ) -> Ant:
        """Run ACO algorithm to generate waypoints"""
        
        rng = random.Random(seed)
        best_ant = None
        best_fitness = float('inf')
        
        for iteration in range(self.MAX_ITERATIONS):
            iteration_ants = []
            
            for ant_id in range(self.ANT_COUNT):
                ant = self._build_ant_path(start, end, route_type, rng)
                
                # Only consider ants that reached the destination
                if len(ant.waypoints) >= self.WAYPOINT_COUNT + 2:
                    iteration_ants.append(ant)
                    
                    if ant.fitness < best_fitness:
                        best_fitness = ant.fitness
                        best_ant = ant
            
            # Evaporate and deposit
            self._evaporate_pheromones()
            if iteration_ants:
                self._deposit_pheromones(iteration_ants)
        
        return best_ant


# =============================================================================
# OSRM INTEGRATION
# =============================================================================

class OSRMConnector:
    """Handles OSRM route drawing using ACO waypoints"""
    
    def __init__(self, base_url: str = "http://router.project-osrm.org"):
        self.base_url = base_url
    
    def draw_route_through_waypoints(
        self, 
        waypoints: List[Waypoint],
        route_type: str = 'driving'
    ) -> Optional[Dict]:
        """Use OSRM to draw real route through waypoints"""
        import requests
        
        if not waypoints or len(waypoints) < 2:
            return None
        
        # Build coordinate string for OSRM
        # Format: lon,lat;lon,lat;...
        coord_string = ";".join([f"{wp.lon},{wp.lat}" for wp in waypoints])
        
        url = f"{self.base_url}/route/v1/{route_type}/{coord_string}"
        params = {
            'overview': 'full',
            'geometries': 'geojson',
            'steps': 'true',
            'annotations': 'true',
        }
        
        try:
            response = requests.get(url, params=params, timeout=15)
            if response.status_code == 200:
                data = response.json()
                if data.get('code') == 'Ok' and data.get('routes'):
                    return data['routes'][0]
        except Exception as e:
            print(f"OSRM error: {e}")
        
        return None
    
    def extract_route_details(self, osrm_route: Dict) -> Dict:
        """Extract route details from OSRM response"""
        if not osrm_route:
            return {}
        
        # Get geometry
        geometry = osrm_route.get('geometry', {})
        coordinates = geometry.get('coordinates', [])
        
        # Get distance and duration
        distance = osrm_route.get('distance', 0)  # meters
        duration = osrm_route.get('duration', 0)  # seconds
        
        # Get legs
        legs = osrm_route.get('legs', [])
        
        return {
            'coordinates': coordinates,  # [lon, lat] format
            'distance_km': distance / 1000,
            'duration_min': duration / 60,
            'legs': legs,
        }


# =============================================================================
# MAIN ACO OPTIMIZER
# =============================================================================

class ACOOptimizer:
    """
    Main ACO Optimizer - Combines ACO waypoint generation with OSRM route drawing
    
    Flow:
    1. ACO generates waypoints using environmental factors
    2. Waypoints are passed to OSRM
    3. OSRM draws real routes through waypoints
    4. Environmental values calculated for final route
    """
    
    def __init__(self):
        self.aco_core = ACOCore()
        self.osrm = OSRMConnector()
    
    def set_real_time_factors(self, factors: RealTimeFactors):
        """Set real-time environmental factors"""
        self.aco_core.set_real_time_factors(factors)
    
    def optimize_route(
        self, 
        start: Tuple[float, float], 
        end: Tuple[float, float],
        route_type: str = 'eco',
        vehicle_type: str = 'electric car'
    ) -> Dict:
        """
        Optimize route using ACO + OSRM
        
        Returns:
            Dictionary with waypoints, route details, environmental values, eco points
        """
        print(f"\n{'='*60}")
        print(f"ACO OPTIMIZATION: {route_type.upper()}")
        print(f"From: {start} To: {end}")
        print(f"{'='*60}")
        
        # Step 1: Generate waypoints using ACO
        print("Step 1: Generating waypoints with ACO...")
        ant = self.aco_core.run_aco(start, end, route_type)
        
        if ant is None or not ant.waypoints:
            print("ACO failed to generate waypoints")
            return self._fallback_result(start, end, route_type, vehicle_type)
        
        print(f"  Generated {len(ant.waypoints)} waypoints")
        
        # Step 2: Draw real route through waypoints using OSRM
        print("Step 2: Drawing real route with OSRM...")
        osrm_route = self.osrm.draw_route_through_waypoints(ant.waypoints)
        
        if osrm_route:
            route_details = self.osrm.extract_route_details(osrm_route)
            actual_distance = route_details.get('distance_km', ant.total_distance_km)
            actual_duration = route_details.get('duration_min', ant.total_time_minutes)
            actual_coordinates = route_details.get('coordinates', [])
        else:
            # Fallback: use waypoint coordinates
            actual_distance = ant.total_distance_km
            actual_duration = ant.total_time_minutes
            actual_coordinates = [(wp.lon, wp.lat) for wp in ant.waypoints]
        
        # Step 3: Calculate environmental values
        print("Step 3: Calculating environmental values...")
        
        # Calculate CO2 emissions
        base_emission = BASE_EMISSIONS.get(vehicle_type.lower(), 120.0)
        co2_emissions = (base_emission * actual_distance) / 1000
        baseline_co2 = 120.0 * actual_distance / 1000
        
        # Calculate eco points
        eco_result = calc_eco_points(
            co2_emissions=co2_emissions,
            baseline_co2=baseline_co2,
            average_aqi=self.aco_core.real_time_factors.air_quality_index,
            traffic_level=self.aco_core.real_time_factors.traffic_congestion,
            time_vs_baseline=0,
            vehicle_type=vehicle_type,
        )
        
        # Build result with Flutter-compatible field names
        result = {
            # Flutter-compatible fields
            'type': route_type.upper(),
            'description': 'Most environmentally friendly route' if route_type == 'eco' else ('Best compromise between time and environment' if route_type == 'balanced' else 'Fastest route - most direct path'),
            'icon': '🌿' if route_type == 'eco' else ('⚖️' if route_type == 'balanced' else '⏱️'),
            
            # Points for map - convert from [lon, lat] to [lat, lon]
            'points': [[coord[1], coord[0]] for coord in actual_coordinates] if actual_coordinates else [{'lat': start[0], 'lon': start[1]}, {'lat': end[0], 'lon': end[1]}],
            
            # Route details - Flutter expects 'distance' and 'duration'
            'distance': round(actual_distance, 2),
            'duration': round(actual_duration, 1),
            
            # Environmental values
            'co2_emissions': round(co2_emissions, 3),
            'co2_savings': round(eco_result.get('co2_savings', 0), 1),
            'eco_points': eco_result['eco_points'],
            
            # Additional fields
            'route_type': route_type,
            'vehicle_type': vehicle_type,
            'averageAQI': self.aco_core.real_time_factors.air_quality_index,
            'trafficLevel': self.aco_core.real_time_factors.traffic_congestion,
            
            # Real-time factors
            'real_time_factors': self.aco_core.real_time_factors.to_dict(),
            
            # Time vs baseline (placeholder)
            'time_vs_baseline': 0,
            
            # ACO metrics
            'aco_fitness': ant.fitness,
            'waypoint_count': len(ant.waypoints),
        }
        
        print(f"  Distance: {result['distance']} km")
        print(f"  Duration: {result['duration']} min")
        print(f"  CO2: {result['co2_emissions']} kg")
        print(f"  Eco Points: {result['eco_points']}")
        
        return result
    
    def _fallback_result(
        self, 
        start: Tuple[float, float], 
        end: Tuple[float, float],
        route_type: str,
        vehicle_type: str
    ) -> Dict:
        """Fallback when ACO fails"""
        # Simple direct route
        distance = self.aco_core._haversine_distance(start, end)
        duration = (distance / 40) * 60
        
        base_emission = BASE_EMISSIONS.get(vehicle_type.lower(), 120.0)
        co2 = (base_emission * distance) / 1000
        
        # Fallback result with Flutter-compatible fields
        return {
            'type': route_type.upper(),
            'description': 'Most environmentally friendly route' if route_type == 'eco' else ('Best compromise between time and environment' if route_type == 'balanced' else 'Fastest route'),
            'icon': '🌿' if route_type == 'eco' else ('⚖️' if route_type == 'balanced' else '⏱️'),
            'points': [{'lat': start[0], 'lon': start[1]}, {'lat': end[0], 'lon': end[1]}],
            'distance': round(distance, 2),
            'duration': round(duration, 1),
            'co2_emissions': round(co2, 3),
            'co2_savings': 0,
            'eco_points': 50,
            'route_type': route_type,
            'vehicle_type': vehicle_type,
            'averageAQI': 50.0,
            'trafficLevel': 0.3,
            'time_vs_baseline': 0,
            'real_time_factors': self.aco_core.real_time_factors.to_dict(),
            'aco_fitness': float('inf'),
            'waypoint_count': 2,
        }
    
    def find_all_routes(
        self, 
        start: Tuple[float, float], 
        end: Tuple[float, float],
        vehicle_type: str = 'electric car'
    ) -> Dict[str, Dict]:
        """
        Find all three route types (eco, balanced, quickest)
        
        Returns:
            Dictionary with 'eco', 'balanced', 'quickest' keys
        """
        print(f"\n{'='*60}")
        print("FINDING ALL ROUTES WITH ACO + OSRM")
        print(f"Start: {start}, End: {end}")
        print(f"Vehicle: {vehicle_type}")
        print(f"{'='*60}")
        
        results = {}
        
        # Eco route
        self.aco_core.real_time_factors = RealTimeFactors.generate(seed=1)
        self.aco_core.real_time_factors.traffic_congestion = 0.3
        results['eco'] = self.optimize_route(start, end, 'eco', vehicle_type)
        
        # Balanced route
        self.aco_core.real_time_factors = RealTimeFactors.generate(seed=2)
        results['balanced'] = self.optimize_route(start, end, 'balanced', vehicle_type)
        
        # Quickest route
        self.aco_core.real_time_factors = RealTimeFactors.generate(seed=3)
        self.aco_core.real_time_factors.traffic_congestion = 0.5
        results['quickest'] = self._get_direct_osrm_route(start, end, vehicle_type)
        
        return results

    def _get_direct_osrm_route(self, start, end, vehicle_type):
        """Get direct route from OSRM without ACO - for quickest route"""
        import requests
        coord = f"{start[1]},{start[0]};{end[1]},{end[0]}"
        url = f"{self.osrm.base_url}/route/v1/driving/{coord}"
        try:
            resp = requests.get(url, params={'overview': 'full', 'geometries': 'geojson'}, timeout=15)
            if resp.status_code == 200:
                data = resp.json()
                if data.get('code') == 'Ok' and data.get('routes'):
                    route = data['routes'][0]
                    details = self.osrm.extract_route_details(route)
                    dist = details.get('distance_km', 0)
                    dur = details.get('duration_min', 0)
                    coords = details.get('coordinates', [])
                    base_em = BASE_EMISSIONS.get(vehicle_type.lower(), 120.0)
                    co2 = (base_em * dist) / 1000
                    return {
                        'type': 'QUICKEST', 'description': 'Fastest route - most direct path',
                        'icon': '⏱️', 'points': [[c[1],c[0]] for c in coords] if coords else [{'lat':start[0],'lon':start[1]},{'lat':end[0],'lon':end[1]}],
                        'distance': round(dist,2), 'duration': round(dur,1), 'co2_emissions': round(co2,3),
                        'co2_savings': 0, 'eco_points': 0, 'route_type': 'quickest', 'vehicle_type': vehicle_type,
                        'averageAQI': 50.0, 'trafficLevel': 0.5, 'time_vs_baseline': 0,
                        'real_time_factors': RealTimeFactors().to_dict(), 'aco_fitness': 0.0, 'waypoint_count': 2,
                    }
        except Exception as e:
            print(f"Direct OSRM error: {e}")
        return self._fallback_result(start, end, 'quickest', vehicle_type)


# API ENDPOINT FUNCTION
# =============================================================================

def handle_aco_route_request(data: Dict) -> Dict:
    """
    Handle ACO route request from API
    
    Expected input:
    {
        "start": [lat, lon],
        "end": [lat, lon],
        "vehicle_type": "electric car"
    }
    """
    start = tuple(data.get('start', [0, 0]))
    end = tuple(data.get('end', [0, 0]))
    vehicle_type = data.get('vehicle_type', 'electric car')
    
    # Validate coordinates
    if start == (0, 0) or end == (0, 0):
        return {'error': 'Invalid coordinates', 'routes': {}}
    
    # Initialize optimizer
    optimizer = ACOOptimizer()
    
    # Find all routes
    routes = optimizer.find_all_routes(start, end, vehicle_type)
    
    return {
        'success': True,
        'start': list(start),
        'end': list(end),
        'vehicle_type': vehicle_type,
        'routes': routes,
        'timestamp': datetime.now().isoformat(),
    }


# =============================================================================
# TEST FUNCTION
# =============================================================================

def test_aco():
    """Test the ACO optimizer"""
    print("=" * 70)
    print("TESTING ACO ROUTE OPTIMIZER")
    print("=" * 70)
    
    # Test coordinates (Kerala region)
    start = (10.0165, 76.3040)  # Near Kochi
    end = (10.5720, 76.1327)     # Near Palakkad
    
    # Initialize optimizer
    optimizer = ACOOptimizer()
    
    # Find all routes
    routes = optimizer.find_all_routes(start, end, 'electric car')
    
    print(f"\n{'='*70}")
    print("FINAL RESULTS")
    print(f"{'='*70}")
    
    for route_type, route in routes.items():
        print(f"\n{route_type.upper()} ROUTE:")
        print(f"  Distance: {route['distance_km']} km")
        print(f"  Duration: {route['duration_min']} min")
        print(f"  CO2: {route['co2_kg']} kg")
        print(f"  Eco Points: {route['eco_points']}")
        print(f"  Badge: {route['eco_badge']}")
        print(f"  Pheromone Level: {route['pheromone_level']:.2f}")
    
    return routes


if __name__ == '__main__':
    test_aco()
